### ISSUE TITLE
Clean up EntityDiff and ItemDiff

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#209]
`EntityDiff` makes assumptions that all entities have aliases, labels, descriptions and claims. It is generally not well designed. `claim` is used as key for statements.

Creating a well designed alternative from ground up might be the way to go.

**Comment by Benestar** [comment]
No longer in this component

**Comment by JeroenDeDauw** [comment]
Well better create a new one for it then ;p https://github.com/wmde/WikibaseDataModelServices/issues/108

**Comment by Benestar** [comment]
It is already tracked on phabricator so I assumed that would be enough.
