### ISSUE TITLE
Move away from entity type + numeric id format in EntityIdValue

### ISSUE THREAD

**Issue by filbertkm** [wmde/WikibaseDataModel#248]
unserializing the EntityIdValue (e.g. from memcached) from the entity type + numeric id format to an EntityId object has significant impact on performance and memory usage.  

The unserialization uses the PropertyId::newFromNumber and ItemId::newFromNumber methods are memory intensive, with use of strtr (#5 in https://github.com/filbertkm/wb-profiling/blob/master/memory_own-itempurge-1.25wmf1.txt).

If we can somehow move away from entity type + numeric id format in EntityIdValue, I think that would be better.

**Comment by JeroenDeDauw** [comment]
Also at https://phabricator.wikimedia.org/T56085

**Comment by thiemowmde** [comment]
Solved via #248.

**Comment by Ladsgroup** [comment]
Just a note, it's fixed via #718, #248 is this PR itself :)

**Comment by thiemowmde** [comment]
#718 was about PHP's native `serialize`, which is unrelated. This issue here was solved with #671.
