### ISSUE TITLE
Remove deprecated claim methods from Entity

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#282]
This is part of #193

**Comment by JeroenDeDauw** [comment]
@thiemowmde this is in fact not done yet

**Comment by JeroenDeDauw** [comment]
Stuff done by https://github.com/wmde/WikibaseDataModel/pull/429 and https://github.com/wmde/WikibaseDataModel/pull/432

**Comment by JeroenDeDauw** [comment]
Also https://github.com/wmde/WikibaseDataModel/pull/428 which is still open

**Comment by thiemowmde** [comment]
What's left:
* `addClaim` is currently used 31 times in my local code base
* `getClaims` is currently used 55 times in my local code base
* `setClaims` (not in `Entity`, but should be removed too) is currently used 9 + 2 times in my local code base

**Comment by JeroenDeDauw** [comment]
The remaining occurrences probably have a high overlap with the OCP violations that block https://phabricator.wikimedia.org/T75496

**Comment by thiemowmde** [comment]
Patches for review:
* https://github.com/wmde/WikibaseInternalSerialization/issues/48
* https://gerrit.wikimedia.org/r/#/c/202389/
