### ISSUE TITLE
Drop PHP 5.3 and 5.4 support

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#611]

**Comment by JeroenDeDauw** [comment]
Any reason to not do this in 5.0 yet?

**Comment by Benestar** [comment]
I don't know when https://gerrit.wikimedia.org/r/#/c/266931/ will be merged. That is the blocker to remove php 5.3 support in Wikibase.git afaik.

**Comment by JeroenDeDauw** [comment]
Oh... looks like fail happened at https://github.com/Wikidata-lib/PropertySuggester/pull/155 then

**Comment by brightbyte** [comment]
MediaWiki 1.27 requires compat with PHP 5.5 [1], and that's what CI at WMF will be running for a while. We are dropping 5.3 and 5.4. I think it will be a while until we can drop support for 5.5.

[1] RFC T118932 sais: "In the IRC meeting it was approved that our minimum version will be the common subset of features supported by PHP 5.5 and HHVM 3.1."

**Comment by JeroenDeDauw** [comment]
Right. Typo in the description fixed.

**Comment by Benestar** [comment]
Patch is merged and PHP 5.5 required. https://lists.wikimedia.org/pipermail/wikitech-l/2016-February/084751.html

**Comment by JeroenDeDauw** [comment]
I had a look at the [publicly listed dependants on DataModel](https://packagist.org/packages/wikibase/data-model/dependents), seems like the stuffs from @addshore, @Tpt and me all requires 5.5 or above already (or rather "already"... :D). So I'm not aware of any users who will be negatively affected by doing this bump.

**Comment by mariushoch** [comment]
+1 Wikibase is already PHP 5.5+ by now, so this wouldn't block us using DM 5.0 immediately.

**Comment by thiemowmde** [comment]
What does "drop support" actually mean? In my opinion, the require tag in the composer.json file should only be touched when this code actually uses a PHP 5.5 feature. Why should the requirement be changed while the code is still compatible?

Or to ask the question an other way: What are you proposing to do to fix this issue?

**Comment by brightbyte** [comment]
Can we do this now?

**Comment by thiemowmde** [comment]
Done in #680.
