### ISSUE TITLE
Add NormalizedString / NormalizedTerm

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#793]
> There should be NormalizedString class. It is easy for developer to forget that Term needs to be created with normalized string only. (`NormalizedString::create($someString, $normalizer)`)

This was a proposal by Aleksey.

**Comment by JeroenDeDauw** [comment]
Two questions:

* what normalization are we talking about here?
* could this not be done in the Term constructor? (that seems like the better place)

**Comment by thiemowmde** [comment]
Let's please have relevant discussions like this on Phabricator.
