### ISSUE TITLE
Add LanguageCode class

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#794]
> There should be a LanguageCode class. It is not just a string, it has certain very specific semantics.

This was a proposal by Aleksey.

**Comment by JeroenDeDauw** [comment]
It is unclear to me if there is any reason to introduce this beyond "encapsulate all primitives". If that is the only reason, then I don't think it is worthwhile to make breaking changes by swapping out the string to a value object everywhere.

Thoughts @addshore @mariushoch @manicki @JonasKress ?

**Comment by thiemowmde** [comment]
Let's please have relevant discussions like this on Phabricator.
