### ISSUE TITLE
Drop EntityId from statement GUID

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#795]
Aleksey wrote:

> Statement ID should be mandatory on domain model level. To achieve this we need to have method addStatement() on an Entity that will generate correct ID (we cannot do it in Statement constructor because we need an entity ID so we will adhere to the current contract <Q1$UUID>)

**Comment by JeroenDeDauw** [comment]
The premise here is that there are costs to having the EntityId in statement GUIDs. Such as not being able to require that each statement has a GUID.

This raises the question: can we get away with dropping the EntityId from statement GUIDs?

I am not aware of any places where we rely on the EntityId bit in the GUID string. Since the GUIDs are part of several public interfaces, usage outside Wikibase should also be considered.

Thoughts @addshore @mariushoch @manicki @JonasKress ?

**Comment by manicki** [comment]
I remember having a conversation about the need of EntityId part if in the statement ID last week, so pinging in @wiese @jakobw.

**Comment by thiemowmde** [comment]
Let's please have relevant discussions like this on Phabricator.

**Comment by addshore** [comment]
This is at least needed right now by SetClaim.php API module in Wikibase.
I haven't looked around for any more but I imagine there are a few.
If we were to get rid of this we would have to provide another way to do the lookup somewhere.

Is the a phab ticket now?

**Comment by wiese** [comment]
Thought we filed that in phab before but could not find it - now opened at https://phabricator.wikimedia.org/T204541
