### ISSUE TITLE
Add LanguageCode class

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#796]
> There should be a LanguageCode class. It is not just a string, it has certain very specific semantics.

This was a proposal by Aleksey. 

---

It is unclear to me if there is any reason to introduce this beyond "encapsulate all primitives". If that is the only reason, then I don't think it is worthwhile to make breaking changes by swapping out the string to a value object everywhere.

Thoughts @addshore @mariushoch @manicki @JonasKress ?

**Comment by mariushoch** [comment]
Hm, do you know what kind of semantics were/are supposed to be reflected there specifically? If not, then I guess this is not actionable.

**Comment by JeroenDeDauw** [comment]
Anyone else see a reason to have such a class? If not, I'll drop this from the list.
