### ISSUE TITLE
Add NormalizedString / NormalizedTerm

### ISSUE THREAD

**Issue by JeroenDeDauw** [wmde/WikibaseDataModel#797]
> There should be NormalizedString class. It is easy for developer to forget that Term needs to be created with normalized string only. (`NormalizedString::create($someString, $normalizer)`)

This was a proposal by Aleksey. 

---

Two questions:

* what normalization are we talking about here?
* could this not be done in the Term constructor? (that seems like the better place)

Thoughts @addshore @mariushoch @manicki @JonasKress ?

**Comment by JeroenDeDauw** [comment]
Thiemo wrote: 

> As far as I'm aware of this refers to
UTF-8/Unicode normalization (removing broken multi-byte characters,
possibly replacing multi-char sequences with single characters that
have the same meaning). Classes for UTF-8 normalization exist. A class
to mark a string as normalized does not exist yet. Have a look at
*HtmlArmor* in MediaWiki core for a possible reference.

**Comment by mariushoch** [comment]
Seems like a sound idea to me... I'm not convinced this actually worth spending time on (is this actually a problem?), but definitely nice to have.

**Comment by JeroenDeDauw** [comment]
Yeah this does not seem like something near the top of the technical priorities list, so closing this.
